    # ========== 卡片 2：今日概览 ==========
    lines.append('    <local:MyCard Title="今日概览" Margin="0,0,0,15" CanSwap="True" IsSwapped="False">')
    lines.append('        <StackPanel Margin="25,40,23,20">')

    lines.append('            <Border CornerRadius="10" Padding="24,16" Margin="0,0,0,16" Background="{DynamicResource ColorBrush7}">')
    lines.append('                <StackPanel>')
    lines.append('                    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center">')
    lines.append('                        <TextBlock Text="' + month + '" FontSize="44" FontWeight="Bold" Foreground="{DynamicResource ColorBrush1}" />')
    lines.append('                        <TextBlock Text=" 月 " FontSize="13" VerticalAlignment="Bottom" Margin="0,0,2,12" Foreground="{DynamicResource ColorBrush3}" />')
    lines.append('                        <TextBlock Text="' + day + '" FontSize="44" FontWeight="Bold" Foreground="{DynamicResource ColorBrush1}" />')
    lines.append('                        <TextBlock Text=" 日" FontSize="13" VerticalAlignment="Bottom" Margin="0,0,0,12" Foreground="{DynamicResource ColorBrush3}" />')
    lines.append('                    </StackPanel>')
    lines.append('                    <TextBlock Text="' + year + ' 年 · 星期' + weekday + '" HorizontalAlignment="Center" FontSize="12" Foreground="{DynamicResource ColorBrush3}" Margin="0,4,0,0" />')
    lines.append('                </StackPanel>')
    lines.append('            </Border>')

    lines.append('            <Border CornerRadius="6" Padding="12,10" Margin="0,0,0,16" Background="{DynamicResource ColorBrush7}">')
    lines.append('                <StackPanel>')
    lines.append('                    <TextBlock Text="每日一言" FontSize="11" Foreground="{DynamicResource ColorBrush3}" Margin="0,0,0,6" />')
    lines.append('                    <TextBlock TextWrapping="Wrap" FontSize="13" Margin="0,0,0,10" Text="' + quote + '" />')
    lines.append('                    <local:MyIconTextButton Height="32" HorizontalAlignment="Right" Padding="16,0,16,0" Text="换一句" LogoScale="0.8" ColorType="Highlight" Logo="M512 128a384 384 0 1 1 0 768 384 384 0 0 1 0-768z M512 192a320 320 0 1 0 0 640 320 320 0 0 0 0-640z M480 288h64v208l144 88-32 56-176-104V288z" EventType="刷新页面" EventData="-" />')
    lines.append('                </StackPanel>')
    lines.append('            </Border>')

    lines.append('            <Grid>')
    lines.append('                <Grid.ColumnDefinitions>')
    lines.append('                    <ColumnDefinition Width="1*" />')
    lines.append('                    <ColumnDefinition Width="1*" />')
    lines.append('                </Grid.ColumnDefinitions>')

    lines.append('                <Border Grid.Column="0" CornerRadius="8" Padding="14,12" Margin="0,0,6,0" Background="{DynamicResource ColorBrush7}">')
    lines.append('                    <StackPanel>')
    lines.append('                        <TextBlock Text="幸运数字" FontSize="11" HorizontalAlignment="Center" Foreground="{DynamicResource ColorBrush3}" Margin="0,0,0,4" />')
    lines.append('                        <TextBlock Text="' + str(lucky_number) + '" FontSize="30" FontWeight="Bold" HorizontalAlignment="Center" Foreground="{DynamicResource ColorBrush1}" />')
    lines.append('                    </StackPanel>')
    lines.append('                </Border>')

    lines.append('                <Border Grid.Column="1" CornerRadius="8" Padding="14,12" Margin="6,0,0,0" Background="{DynamicResource ColorBrush7}">')
    lines.append('                    <StackPanel>')
    lines.append('                        <TextBlock Text="幸运颜色" FontSize="11" HorizontalAlignment="Center" Foreground="{DynamicResource ColorBrush3}" Margin="0,0,0,6" />')
    lines.append('                        <StackPanel Orientation="Horizontal" HorizontalAlignment="Center">')
    lines.append('                            <Border Width="16" Height="16" CornerRadius="4" Background="' + lucky_color["hex"] + '" Margin="0,0,8,0" VerticalAlignment="Center" />')
    lines.append('                            <TextBlock Text="' + lucky_color["name"] + '" FontSize="15" FontWeight="Bold" VerticalAlignment="Center" Foreground="' + lucky_color["hex"] + '" />')
    lines.append('                        </StackPanel>')
    lines.append('                    </StackPanel>')
    lines.append('                </Border>')
    lines.append('            </Grid>')

    lines.append('        </StackPanel>')
    lines.append('    </local:MyCard>')

